### ISSUE TITLE
Breaks google image search results 

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/Remove-Google-Redirection#1]
- The link on the thumbnail is broken
- The link on the caption below is OK

## With extension 
![Screen shot 2019-04-28 at 00 23 47](https://user-images.githubusercontent.com/49612/56856137-0abb7880-694c-11e9-91bd-13fdc402f472.png)

## Without extension 
![Screen shot 2019-04-28 at 00 24 23](https://user-images.githubusercontent.com/49612/56856138-0beca580-694c-11e9-8bee-18ebe3ea23b8.png)

**Comment by gingerbeardman** [comment]
Already reported upstream as https://github.com/kodango/Remove-Google-Redirection/issues/9

**Comment by yimingliu** [comment]
I am aware of this.  In addition to this problem, the extension also breaks links from Google's home page, during special events and such.  Ideally I'd prefer to just roll in a fix from upstream (since my Javascript skill is actually not great), but it's been awhile and no fix seems forthcoming.  I might try to figure this out if/when I find some time.

**Comment by yimingliu** [comment]
This is hopefully fixed.  Let me know if it doesn't work, or if it introduced regressions elsewhere.

**Comment by gingerbeardman** [comment]
@yimingliu fixed! thanks

**Comment by gingerbeardman** [comment]
One annoyance is that since this fix, clicking the image opens the image rather than showing more information or even opening the URL of the page the image is on (which is where the link below the image goes).

Shall I open another issue?

**Comment by yimingliu** [comment]
On this one, I'm not sure what you mean.

Can you open a new issue and describe what the desired behavior is, and the current behavior with the app extension (screenshots and such very helpful).  I'll definitely see what I can do.
